### ISSUE TITLE
Failed to open application details on Android device.

### ISSUE THREAD

**Issue by darkstarx** [yanncabral/open_settings_plus#4]
Package: `open_settings_plus: ^0.1.0`
Device: `Poco F3 Android 13`

```
E/MethodChannel#open_settings_plus( 7816): Failed to handle method call
E/MethodChannel#open_settings_plus( 7816): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS flg=0x10000000 }
E/MethodChannel#open_settings_plus( 7816): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2206)
E/MethodChannel#open_settings_plus( 7816): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1841)
E/MethodChannel#open_settings_plus( 7816): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
E/MethodChannel#open_settings_plus( 7816): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
E/MethodChannel#open_settings_plus( 7816): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
E/MethodChannel#open_settings_plus( 7816): 	at br.com.yanncabral.open_settings_plus.OpenSettingsPlusPlugin.handleJumpToSettings(OpenSettingsPlusPlugin.kt:33)
E/MethodChannel#open_settings_plus( 7816): 	at br.com.yanncabral.open_settings_plus.OpenSettingsPlusPlugin.onMethodCall(OpenSettingsPlusPlugin.kt:42)
E/MethodChannel#open_settings_plus( 7816): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#open_settings_plus( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#open_settings_plus( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#open_settings_plus( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#open_settings_plus( 7816): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#open_settings_plus( 7816): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#open_settings_plus( 7816): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MethodChannel#open_settings_plus( 7816): 	at android.os.Looper.loop(Looper.java:299)
E/MethodChannel#open_settings_plus( 7816): 	at android.app.ActivityThread.main(ActivityThread.java:8261)
E/MethodChannel#open_settings_plus( 7816): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#open_settings_plus( 7816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/MethodChannel#open_settings_plus( 7816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[Profile] I 2024-01-25 11:25:20.318767 Profile saved in the local storage.
[Profile] I 2024-01-25 11:25:20.319398 Profile saved in the local storage.
E/flutter ( 7816): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS flg=0x10000000 }, null, android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS flg=0x10000000 }
E/flutter ( 7816): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2206)
E/flutter ( 7816): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1841)
E/flutter ( 7816): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1111)
E/flutter ( 7816): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1082)
E/flutter ( 7816): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
E/flutter ( 7816): 	at br.com.yanncabral.open_settings_plus.OpenSettingsPlusPlugin.handleJumpToSettings(OpenSettingsPlusPlugin.kt:33)
E/flutter ( 7816): 	at br.com.yanncabral.open_settings_plus.OpenSettingsPlusPlugin.onMethodCall(OpenSettingsPlusPlugin.kt:42)
E/flutter ( 7816): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 7816): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7816): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 7816): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7816): 	at android.os.Looper.loopOnce(Looper.java:210)
E/flutter ( 7816): 	at android.os.Looper.loop(Looper.java:299)
E/flutter ( 7816): 	at android.app.ActivityThread.main(ActivityThread.java:8261)
E/flutter ( 7816): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7816): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/flutter ( 7816): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
E/flutter ( 7816): )
E/flutter ( 7816): #0      StandardMethodCodec.decodeEnvelope
E/flutter ( 7816): #1      MethodChannel._invokeMethod
E/flutter ( 7816): <asynchronous suspension>
E/flutter ( 7816): #2      MethodChannelOpenSettingsPlus.sendMessageToNative
E/flutter ( 7816): <asynchronous suspension>
E/flutter ( 7816):
```

**Comment by darkstarx** [comment]
Ok, there is a mistake. The fix is here #5
